# Dependencies
markdown:         kramdown

# Permalinks
permalink: /:year/:month/:title.html
# relative_permalinks: true

# Setup
title:            A Statistics Blog
tagline:          ''
description:      'Statstics education with R, and related geekery.'
baseurl: "/knitr-hyde/" # the subpath of your site, e.g. /blog/
url: "https://homerhanumat.github.io" # the base hostname & protocol for your site

author:
  name:           'Homer White'
  url:            https://statistics.rainandrhino.org

github:
  repo:           https://github.com/homerhanumat/knitr-hyde
